#!/bin/bash

# PixelTrack - GitHub Actions Setup Guide
# Bu script GitHub Actions'ı kurmak için gerekli adımları açıklar

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   PixelTrack - GitHub Actions Setup                      ║"
echo "║   Email Tracking System CI/CD Configuration              ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 GitHub Secrets'a eklenmesi gereken değişkenler:"
echo ""
echo "1️⃣  SUPABASE_ACCESS_TOKEN"
echo "   ├─ Nereden al: https://app.supabase.com/account/tokens"
echo "   ├─ Tür: Personal API Token"
echo "   └─ Bu token Edge Functions deploy etmek için gerekli"
echo ""
echo "2️⃣  SUPABASE_PROJECT_ID"
echo "   ├─ Değer: jnlbhiyazvexttfpuxxe"
echo "   └─ (Bu zaten workflow'da tanımlanmış)"
echo ""
echo "📝 GitHub Secret Ekleme Adımları:"
echo ""
echo "1. GitHub repository'nin settings'e git:"
echo "   Settings → Secrets and variables → Actions"
echo ""
echo "2. 'New repository secret' butonuna tıkla"
echo ""
echo "3. Aşağıdaki değerleri ekle:"
echo ""
echo "   Name: SUPABASE_ACCESS_TOKEN"
echo "   Secret: <Supabase tokens sayfasından copy et>"
echo ""
echo "4. Save'e basıp tamamla"
echo ""
echo "✅ Workflow Tetiklemek:"
echo ""
echo "   git add ."
echo "   git commit -m 'Setup: Email tracking system'"
echo "   git push origin main"
echo ""
echo "   💡 Workflow otomatik çalışır!"
echo ""
echo "📊 Deployment Status:"
echo "   Settings → Actions → General → Allow all actions"
echo "   Actions → Deploy to Supabase → Workflow runs"
echo ""
echo "🔗 Supabase Access Token Al:"
echo "   https://app.supabase.com/account/tokens"
echo ""
echo "✨ Hepsi bitti! Edge Functions otomatik deploy olacak."
